# Use an official Node.js runtime as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Set the default command to execute JavaScript code using Node.js
CMD ["bash", "-c", "node user_code.js < input.txt"]
